[Eth]
NetworkId = 714
SyncMode = "full"
NoPruning = false
NoPrefetch = false
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TriesInMemory = 128
TrieTimeout = 3600000000000
EnablePreimageRecording = false

[Eth.Miner]
GasCeil = 40000000
GasPrice = 10000000000
Recommit = 10000000000
DelayLeftOver = 50000000

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil= "0"
ValidatorCommission = 1000
BidSimulationLeftOver = 50000000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63aBCd2b9b1baa327f2Dda0f873F197ccd186"

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 10000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = true
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
StaticNodes = []
TrustedNodes = []
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "debug"
FileRoot = ""